# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tootieapp', '0002_auto_20160624_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tootieapp.Village'),
            preserve_default=False,
        ),
    ]
